# Generated by Django 3.0.7 on 2020-06-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_boast', models.BooleanField()),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField(default=0, editable=False)),
                ('down_votes', models.IntegerField(default=0, editable=False)),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
