# Generated by Django 3.0.7 on 2020-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_ghostpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
